package org.enricogiurin.ocp17.book.ch10;

import java.util.stream.Collectors;
import java.util.stream.IntStream;

public class Teeing {

  public static void main(String[] args) {
    new Teeing().teeing();
  }

  //partially generated by chatGPT
  void teeing() {
    IntStream intStream = IntStream.rangeClosed(1, 10);
    Data collect = intStream.boxed()
        .collect(
            Collectors.teeing(
                Collectors.summingInt(Integer::intValue),
                Collectors.reducing(1, (a, b) -> a * b),
                Data::new));
    System.out.println("sum is: " + collect.sum());  //sum is: 55
    System.out.println("product is: " + collect.product());  //product is: 3628800

  }
}

record Data(int sum, int product) {

}
