package org.enricogiurin.ocp17.book.ch10;

import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public class UseOfFlatMap {

  public static void main(String[] args) {
    new UseOfFlatMap().getAllAuthors();
  }

  //partially generated by chatGPT
  void getAllAuthors() {
    List<Book> books = List.of(
        new Book("Book 1", List.of("Author 1", "Author 2")),
        new Book("Book 2", List.of("Author 3")),
        new Book("Book 3", List.of("Author 4", "Author 5"))
    );
    // FlatMap to extract authors
    List<String> allAuthors = books.stream()
        .flatMap(book -> book.authors().stream())
        .collect(Collectors.toList());
    System.out.println(allAuthors);
  }

  void flatMap() {
    List<Integer> listA = List.of(1, 2, 3, 4, 5);
    List<Integer> listB = List.of(6, 7, 8, 9, 10);
    //we merge two list
    Stream.of(listA, listB)
        .flatMap(list -> list.stream())
        .forEach(System.out::println);  //1...10
  }


  record Book(String title, List<String> authors) {

  }
}




