package org.enricogiurin.ocp17.book.ch7.nested.inner;

//generated by Chat GPT

import java.util.UUID;
import org.enricogiurin.ocp17.book.ch7.nested.inner.University.Department.Professor;

/**
 * Example of nested classes, from OCP book. The outer class is University, which has two inner
 * classes: Department and Student.
 */
public class University {

  private String id;

  public University() {
    this.id = UUID.randomUUID().toString();
  }

  void createProfessor() {
    Professor professor = new University().new Department().new Professor("Dr. Ross");
    professor.printID();
  }

  void createProfessorMultiLines() {
    University university = new University();
    University.Department department = university.new Department();
    University.Department.Professor professor = department.new Professor("Dr. Smith");
    professor.printID();
  }

  void createProfessorInOneLine(){
    //using a single line
    Professor johnDoe = new University().new Department().new Professor("John Doe");
    System.out.println(johnDoe.name);
  }

  public static void main(String[] args) {
    University university = new University();
    university.createProfessor();
    System.out.println();
    university.createProfessorMultiLines();
    university.createProfessorInOneLine();
  }

  class Department {
    private String id;
    Department() {
      this.id = UUID.randomUUID().toString();
    }

    class Professor {
      private String name;
      private String id;

      Professor(String name) {
        this.name = name;
        this.id = UUID.randomUUID().toString();
      }

      void printID() {
        System.out.println("University id: " + University.this.id);
        //System.out.println("University id: "+this.id); //equivalent
        System.out.println("Department id: " + University.Department.this.id);
        // System.out.println("Department id: "+Department.this.id); //equivalent
        System.out.println("professor id: " + University.Department.Professor.this.id);
        //System.out.println("professor id: "+Professor.this.id);//equivalent
      }
    }
  }
}
