package org.enricogiurin.ocp17.ch14.io;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;

public class copyStream {

  public static void main(String[] args) throws IOException {
    new copyStream().copyFileRightVersion();
  }


  //basic usage, no buffer
  void copyStream(InputStream inputStream, OutputStream outputStream) throws IOException {
    int b;
    while ((b= inputStream.read())!=-1){
      outputStream.write(b);
    }
  }



  //wrong way to copy file
  //It will only correctly copy files whose character count is a multiple of 10,
  public void wrongWayCopyFile() throws IOException {
    //contents : 12345678901
    File file1 = new File("/tmp/source.txt");
    //12345678901
    //34567890
    //~
    File file2 = new File("/tmp/dest.txt");
    var reader = new InputStreamReader(new FileInputStream(file1));
    try (var writer = new FileWriter(file2)) {
      char[] buffer = new char[10];
      while (reader.read(buffer) != -1) {
        //the buffer can contains previous read
        System.out.println("buffer: " + new String(buffer));
        writer.write(buffer);
      }
    }

  }


  //generated by chatGPT
  public void copyFileRightVersion() throws IOException {
    //contents : 12345678901
    File file1 = new File("/tmp/source.txt");

    //final contents of the file: 12345678901
    File file2 = new File("/tmp/dest.txt");
    try (var reader = new InputStreamReader(new FileInputStream(file1));
        var writer = new FileWriter(file2)) {
      char[] buffer = new char[10];
      int bytesRead;
      while ((bytesRead = reader.read(buffer)) != -1) {
        //I only copy the characters effectively read
        writer.write(buffer, 0, bytesRead); // Corrected line
      }
    }
  }

}