package org.enricogiurin.ocp17.ch7.sealed;

public sealed interface Shape permits Circle {

}
//A sealed interface restricts which subclasses may implement it.

//sealed, non-sealed or final modifiers expected
//example generated by chatgpt
final class Circle implements Shape {

  private double radius;

  public Circle(double radius) {
    this.radius = radius;
  }

  public double getRadius() {
    return radius;
  }

  public double calculateArea() {
    return Math.PI * radius * radius;
  }
}
