package org.enricogiurin.ocp17.book.ch7.useofenum;

//generated by chatgpt
public enum SeasonWithValues {

  SPRING("Spring is the season of renewal and new beginnings.") {
    //we can define methods only on specific enum
    public String getMood() {
      return "happiness";
    }
  },
  SUMMER("Summer is the season of warmth and sunshine."),
  AUTUMN("Autumn is the season of harvest and falling leaves."),
  WINTER("Winter is the season of cold and snow.");//semicolon here is mandatory

  private String description;

  SeasonWithValues(String description) {
    System.out.println("building description for " + this.name());
    this.description = description;
  }

  //this is the default method, but we are not forced to define!
  public String getMood() {
    return "default";
  }


  public String getDescription() {
    return description;
  }
}

class Main {

  public static void main(String[] args) {
    SeasonWithValues spring = SeasonWithValues.SPRING;
    SeasonWithValues spring2 = SeasonWithValues.SPRING;
    System.out.println(spring.getMood());
    System.out.println(SeasonWithValues.WINTER.getMood());
  }
}
