package org.enricogiurin.ocp17.book.ch7.interfaces.defaultmethods;

/**
 *  Default methods in this interface demonstrate their ability to invoke other types of methods,
 *  showcasing the flexibility and integration of different method types.
 */
public class DefaultMethodCallingOtherMethods {

  public static void main(String[] args) {
    var dataOperations = new DataOperationsImpl();
    //This is a default operation.
    //This is another default operation.
    //This is a static operation.
    //This is a private static operation.
    //This is a public instance operation.
    //This is a private instance operation.
    dataOperations.defaultOperation();
  }
}

//Template partially generated by CGPT
interface DataOperations {
  // Default Method
  // a default method can invoke any other type of method
  default void defaultOperation() {
    System.out.println("This is a default operation.");
    anotherDefaultOperation();
    staticOperation();  //calling public static method
    privateStaticOperation(); //calling private static method
    publicInstanceOperation();  //calling public instance method
    privateInstanceOperation(); //calling private instance method
  }

  default void anotherDefaultOperation() {
    System.out.println("This is another default operation.");
  }

  // Public Static Method
  static void staticOperation() {
    System.out.println("This is a static operation.");
  }

  // Private Static Method
  private static void privateStaticOperation() {
    System.out.println("This is a private static operation.");
  }

  // Public Instance Method
  void publicInstanceOperation();

  // Private Instance Method
  private void privateInstanceOperation() {
    System.out.println("This is a private instance operation.");
  }
}

class DataOperationsImpl implements DataOperations {
  @Override
  public void publicInstanceOperation() {
    System.out.println("This is a public instance operation.");
  }
}



